SET(TOOLBOX_NUMERICBAR_DIR ${PROJECT_SOURCE_DIR}/src/viewer/toolbox/NumericBar)

SET(TOOLBOX_NUMERICBAR_SRCS
  ${TOOLBOX_NUMERICBAR_DIR}/numericbar.cpp
)

SET(TOOLBOX_NUMERICBAR_MOC_HDRS
  ${TOOLBOX_NUMERICBAR_DIR}/numericbar.h

)